language: node_js
node_js:
  - "lts/*"
addons:
  apt:
    update: true
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - sudo apt-get install -y default-jdk
install:
  - yarn install
  - yarn setup
script:
  - yarn build
after_script:
  - yarn coverage && nyc report --reporter=text-lcov | coveralls
