# -*- mode: ruby -*-
# vi: set ft=ruby :

$initScript = <<-"SCRIPT"
  MONGOD_CONF_FILE="/etc/mongodb.conf"
  ELASTICSEARCH_CONF_FILE="/etc/elasticsearch/elasticsearch.yml"
  NODE_VERSION="8.x"
  IPTABLES_RULES="/etc/iptables.up.rules"
  NETWORK_PRE_HOOK="/etc/network/if-pre-up.d/iptables"

  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y mongodb \
                                                    iftop \
                                                    lsof \
                                                    apt-transport-https \
                                                    gnupg \
                                                    dirmngr \
                                                    vim \
                                                    htop \
                                                    build-essential \
                                                    openjdk-8-jdk-headless

  iptables -P INPUT ACCEPT
  iptables -P FORWARD ACCEPT
  iptables -P OUTPUT ACCEPT
  iptables -t nat -F
  iptables -t mangle -F
  iptables -F
  iptables -X
  iptables -I INPUT -i lo -j ACCEPT
  iptables -I INPUT ! -i lo -d 127.0.0.0/8 -j REJECT
  iptables -I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
  iptables -I OUTPUT -j ACCEPT
  iptables -I INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
  iptables -I INPUT -p tcp -m state --state NEW -m tcp --dport 2222 -j ACCEPT
  iptables -I INPUT -p tcp -m state --state NEW -m tcp --dport 9200 -j ACCEPT
  iptables -I INPUT -p tcp -m state --state NEW -m tcp --dport 9201 -j ACCEPT
  iptables -I INPUT -p tcp -m state --state NEW -m tcp --dport 27007 -j ACCEPT
  iptables -I INPUT -p tcp -m state --state NEW -m tcp --dport 27017 -j ACCEPT
  iptables -I INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
  iptables -I INPUT -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 7
  # iptables -I INPUT -j REJECT
  iptables -I FORWARD -j REJECT

  iptables-save > $IPTABLES_RULES

  tee -a $NETWORK_PRE_HOOK <<-"EOF"
#!/bin/sh
/sbin/iptables-restore < /etc/iptables.up.rules
EOF

  chmod +x $NETWORK_PRE_HOOK

  apt-key adv --fetch-keys https://artifacts.elastic.co/GPG-KEY-elasticsearch
  apt-key adv --fetch-keys https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-6.x.list
  echo "deb https://deb.nodesource.com/node_${NODE_VERSION} $(lsb_release -c -s) main" | tee -a /etc/apt/sources.list.d/nodejs.list
  echo "deb-src https://deb.nodesource.com/node_${NODE_VERSION} $(lsb_release -c -s) main" | tee -a /etc/apt/sources.list.d/nodejs.list

  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y elasticsearch nodejs

  sed -i 's/^bind_ip/#bind_ip/g' $MONGOD_CONF_FILE
  sed -i 's/^#network\.host: 192.168.0.1/network\.host: 0.0.0.0/g' $ELASTICSEARCH_CONF_FILE
  sed -i 's/^#http\.port: 9200/http\.port: 9201/g' $ELASTICSEARCH_CONF_FILE

  systemctl restart mongodb.service
  systemctl enable elasticsearch
  systemctl restart elasticsearch

  # Elasticsearch takes long to start
  sleep 15
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define :sugarcube do |sc|
    # sc.vm.network :private_network, ip: "192.168.42.100"
    sc.vm.network "forwarded_port", guest: 27017, host: 27007
    sc.vm.network "forwarded_port", guest: 9201, host: 9200
    sc.vm.provision "shell", inline: $initScript
    sc.vm.synced_folder ".",
                        "/vagrant",
                        type: "rsync",
                        rsync__args: ["-a", "-z"],
                        rsync__excludes: ["data", "node_modules"],
                        rsync__verbose: true
  end
end
